---
sysctl_config:
  net.ipv4.ip_forward: 1 
  net.ipv6.conf.all.forwarding: 1 
  net.ipv4.conf.all.accept_redirects: 0 
  net.ipv4.conf.all.send_redirects: 0
  net.ipv4.conf.all.accept_source_route: 0
  net.ipv4.conf.all.secure_redirects: 0
  net.ipv4.conf.all.log_martians: 1
  net.ipv4.conf.default.send_redirects: 0
  net.ipv4.conf.default.accept_source_route: 0
  net.ipv4.conf.default.accept_redirects: 0
  net.ipv4.conf.default.secure_redirects: 0
  net.ipv4.icmp_ignore_bogus_error_responses: 1
  net.ipv4.tcp_syncookies: 1
  net.ipv4.conf.all.rp_filter: 0
  net.ipv4.tcp_mtu_probing: 1
  net.ipv4.icmp_echo_ignore_broadcasts: 1
  net.ipv4.conf.eth0.disable_xfrm: 0
  net.ipv4.conf.eth0.disable_policy: 0
